### ISSUE TITLE
After initial sync with owncloud 7 events are no longer synced from server to phone

### ISSUE THREAD

**Issue by Zotan** [nemomobile/buteo-sync-plugin-caldav#39] opened 2014-10-27 00:12 UTC
After setting up a caldav account with my owncloud 7 server appointments are no longer being synced to the device. At account creation I think everything was synced correctly and new events created on the phone are propagated to the server. In the journal I see lots of errors of the form:

NotebookSyncAgent::updateIncidences:666 - Unable to add incidence "7c379424-742e-4136-89e8-dd94d4b11e9b" to notebook "87a6db4a-18e5-4e44-a990-d73b870d81f1" 
CalDAV sync failed: 401 "unable to write notebook changes"

and occasional errors of the form:

mKCal::SqliteFormat::modifyComponents:503 - sqliteformat.cpp: 503 - failed to modify attendees for incidence "4020159d-2075-4bb8-acbd-9a9afe66ac2f" 
CalDavClient::syncFinished:333 - CalDAV sync failed: 403 "unable to save calendar storage" 

Is there anything other log info that would be useful?

**Comment by BlackIkeEagle** [comment] 2015-01-02 20:28
Same issue here:
Jan 02 21:27:44 Jolla caldav-client[24549]: [W] mKCal::SqliteStorage::open:179 - sqlitestorage.cpp: 179 - database "/home/nemo/.local/share/system/privileged/Calendar/mkcal/db" opened 
Jan 02 21:27:52 Jolla caldav-client[24549]: [C] CalDavClient::notebookSyncFinished:485 - Notebook sync finished. Total agents: 6 
Jan 02 21:27:53 Jolla caldav-client[24549]: [C] CalDavClient::notebookSyncFinished:485 - Notebook sync finished. Total agents: 6 
Jan 02 21:27:53 Jolla caldav-client[24549]: [C] CalDavClient::notebookSyncFinished:485 - Notebook sync finished. Total agents: 6 
Jan 02 21:27:54 Jolla caldav-client[24549]: [C] CalDavClient::notebookSyncFinished:485 - Notebook sync finished. Total agents: 6 
Jan 02 21:27:55 Jolla caldav-client[24549]: [C] CalDavClient::notebookSyncFinished:485 - Notebook sync finished. Total agents: 6 
Jan 02 21:27:58 Jolla kernel: misc memnotify: 0xedd23000 - threshold updated to 0x1
Jan 02 21:28:01 Jolla caldav-client[24549]: [C] CalDavClient::notebookSyncFinished:485 - Notebook sync finished. Total agents: 6 
Jan 02 21:28:01 Jolla caldav-client[24549]: [C] NotebookSyncAgent::updateIncidences:859 - Unable to add incidence "0df13ca7-de78-4191-9d61-9f107722f0e1" to notebook "4960139c-071d-456f-b90f-56f93ba27202" 
Jan 02 21:28:01 Jolla caldav-client[24549]: [C] CalDavClient::syncFinished:333 - CalDAV sync failed: 401 "unable to write notebook changes"

**Comment by chriadam** [comment] 2015-02-04 03:58
Is that with `MSYNCD_LOGGING_LEVEL=8 devel-su -p msyncd` or a lower logging level?  It looks like the notebook might have been marked as read-only on the device prior to the attempted update of the event.  If you're able to provide more information that would be helpful for me to track down where and why.

Thanks!

**Comment by BlackIkeEagle** [comment] 2015-02-04 21:22
@chriadam Yes that is with the logging level to 8, but i had the impression that the other (non debug) info was no longer there.

**Comment by chriadam** [comment] 2015-02-05 01:29
Ah, maybe a separate/different env var is needed to tell mkcal to output debugging info.  I'll look into it later today.

**Comment by chriadam** [comment] 2015-04-08 03:29
This one slipped through the cracks, somehow.  The environment variable is KCALDEBUG=1.
I suspect that this one should be fixed with the latest bleeding edge code, but let's wait and see.

**Comment by BlackIkeEagle** [comment] 2015-04-09 11:44
do you want me to create a test account on my owncloud so you can test while developing ?

**Comment by chriadam** [comment] 2015-08-03 02:25
Yes please - are you able to send me the account details plus repro steps to chris dot adams at jolla dot com and I will investigate further.

**Comment by BlackIkeEagle** [comment] 2015-08-03 14:42
I'm sorry I did forget about this issue, currently I have SailfishOS 1.1.7.25 and all seems to work fine.

so no more steps to reproduce.

**Comment by chriadam** [comment] 2015-08-04 09:59
Thank you.  I apologise for my late responses!

**Comment by chriadam** [comment] 2015-08-04 09:59
Closing issue as per above comments.

**Closed by chriadam** 2015-08-04 09:59 UTC
