### ISSUE TITLE
Sync is confused by daylight savings time

### ISSUE THREAD

**Issue by birefringence** [nemomobile/buteo-sync-plugin-caldav#50] opened 2015-04-03 06:12 UTC
After the DST switch last weekend all my synched events are off by one our. I've checked the content of the mkcal database and for an event that is supposed to start at Thu, 02 Apr 2015 13:00:00 GMT+2 (Europe/Berlin with DST) I find:

    DateStart = 1427976000
    DateStartLocal = 1427979600
    StartTimeZone = Europe/Berlin

You can see that the DateStartLocal is actually correct (13:00 local time), while the DateStart is off by one hour (12:00 GMT, but should be 11:00 GMT). The Jolla calendar shows 14:00 as the start time.

This is the data stored in the CalDAV Server (Baikal):

    VERSION:2.0
    PRODID:-//EGroupware//NONSGML EGroupware Calendar 1.9.004//DE
    BEGIN:VTIMEZONE
    TZID:Europe/Berlin
    X-LIC-LOCATION:Europe/Berlin
    BEGIN:DAYLIGHT
    TZOFFSETFROM:+0100
    TZOFFSETTO:+0200
    TZNAME:CEST
    DTSTART:19700329T020000
    RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
    END:DAYLIGHT
    BEGIN:STANDARD
    TZOFFSETFROM:+0200
    TZOFFSETTO:+0100
    TZNAME:CET
    DTSTART:19701025T030000
    RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
    END:STANDARD
    END:VTIMEZONE
    BEGIN:VEVENT
    CLASS:PUBLIC
    SUMMARY:REDACTED
    DTSTART;TZID=Europe/Berlin:20150402T130000
    DTEND;TZID=Europe/Berlin:20150402T140000
    PRIORITY:5
    TRANSP:OPAQUE
    CATEGORIES:REDACTED
    UID:calendar-42066-f2bd5fa3746e5d6bdbfac09ac22cc8c2
    STATUS:CONFIRMED
    CREATED:20150330T152325Z
    LAST-MODIFIED:20150330T152325Z
    DTSTAMP:20150330T154508Z
    END:VEVENT
    END:VCALENDAR

Other people seem to experience this as well, see:
https://together.jolla.com/question/60486/all-dates-shifted-by-one-hour-in-calendar-after-updating-to-11038/
https://together.jolla.com/question/86562/daylight-saving-time-confuses-calendar/

**Comment by chriadam** [comment] 2015-04-07 01:25
@pvuorela @blammit any ideas about this one?  When I sync, do I have to manually apply some offset to the DTSTART, or does kcal's icalformat processing handle the DAYLIGHT data automatically?

**Comment by chriadam** [comment] 2015-04-16 05:48
I tried to determine whether it was kcal's icalformat handling which is broken, or something we do in the caldav sync plugin.  I believe that the following program illustrates that the error is indeed in the caldav plugin:

    #include <extendedcalendar.h>
    #include <extendedstorage.h>
    #include <notebook.h>
    #include <incidence.h>
    #include <icalformat.h>
    #include <memorycalendar.h>
    
    int test()
    {
        QByteArray icalData =
    "BEGIN:VCALENDAR\r\n"
    "VERSION:2.0\r\n"
    "PRODID:-//EGroupware//NONSGML EGroupware Calendar 1.9.004//DE\r\n"
    "BEGIN:VTIMEZONE\r\n"
    "TZID:Europe/Berlin\r\n"
    "X-LIC-LOCATION:Europe/Berlin\r\n"
    "BEGIN:DAYLIGHT\r\n"
    "TZOFFSETFROM:+0100\r\n"
    "TZOFFSETTO:+0200\r\n"
    "TZNAME:CEST\r\n"
    "DTSTART:19700329T020000\r\n"
    "RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3\r\n"
    "END:DAYLIGHT\r\n"
    "BEGIN:STANDARD\r\n"
    "TZOFFSETFROM:+0200\r\n"
    "TZOFFSETTO:+0100\r\n"
    "TZNAME:CET\r\n"
    "DTSTART:19701025T030000\r\n"
    "RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10\r\n"
    "END:STANDARD\r\n"
    "END:VTIMEZONE\r\n"
    "BEGIN:VEVENT\r\n"
    "CLASS:PUBLIC\r\n"
    "SUMMARY:REDACTED\r\n"
    "DTSTART;TZID=Europe/Berlin:20150402T130000\r\n"
    "DTEND;TZID=Europe/Berlin:20150402T140000\r\n"
    "PRIORITY:5\r\n"
    "TRANSP:OPAQUE\r\n"
    "CATEGORIES:REDACTED\r\n"
    "UID:calendar-42066-f2bd5fa3746e5d6bdbfac09ac22cc8c2\r\n"
    "STATUS:CONFIRMED\r\n"
    "CREATED:20150330T152325Z\r\n"
    "LAST-MODIFIED:20150330T152325Z\r\n"
    "DTSTAMP:20150330T154508Z\r\n"
    "END:VEVENT\r\n"
    "END:VCALENDAR\r\n\r\n";
    
        KCalCore::ICalFormat iCalFormat;
        mKCal::ExtendedCalendar::Ptr calendar = mKCal::ExtendedCalendar::Ptr(new mKCal::ExtendedCalendar(KDateTime::Spec::UTC()));
        mKCal::ExtendedStorage::Ptr storage = mKCal::ExtendedCalendar::defaultStorage(calendar);
        if (!storage->open()) {
            qWarning() << "could not open calendar";
            return 1;
        }
        if (!iCalFormat.fromString(calendar, icalData)) {
            qWarning() << "ical import failed!";
            return 1;
        }
        KCalCore::Event::List events = calendar->events();
        Q_FOREACH (KCalCore::Event::Ptr evt, events) {
            qWarning() << "event:" << evt->dtStart().toString() << evt->dtEnd().toString();
        }
        storage->save();
        storage->close();
        calendar->close();
        return 0;
    }

Running that and then doing: devel-su -p sqlite3 /home/nemo/.local/share/system/privileged/Calendar/mkcal/db "select * from Components;"

shows:

DateStart INTEGER, DateStartLocal INTEGER
1427972400|1427979600

Note that the DateStart value here is 1427972400 - contrast that with the value reported above of 1427976000 which is a difference of 3600 (which I assume is one hour, assuming second resolution).

**Comment by chriadam** [comment] 2015-04-16 06:24
Hrm, actually, if I set my phone's date/time settings to be in Berlin timezone, and then re-run my test application, I see the problem as reported - ie, the DateStart has 1427976000 ..

**Comment by chriadam** [comment] 2015-04-16 06:34
https://github.com/mer-packages/mkcal/blob/master/src/sqliteformat.cpp#L219

**Comment by chriadam** [comment] 2015-04-16 07:22
When I add the following debug output to the toOriginTime function:
qWarning() << "++++++++++ have dt=" << dt.toString() << "which is UTC:" << dt.toUtc() << "so returning:" << d->mOriginTime.secsTo_long(dt.isUtc() ? dt : dt.toUtc());

I then set the system date/time settings on my device to "Brisbane" and run my test function from above, we get:

[W] mKCal::SqliteStorage::toOriginTime:2992 - ++++++++++ have dt= "2015-04-02T13:00:00+02:00" which is UTC: "2015-04-02T11:00:00Z" so returning: 1427972400 
[W] mKCal::SqliteStorage::toOriginTime:2992 - ++++++++++ have dt= "2015-04-02T14:00:00+02:00" which is UTC: "2015-04-02T12:00:00Z" so returning: 1427976000

If I then set the system date/time timezone to Berlin and run the test again, we get:

[W] mKCal::SqliteStorage::toOriginTime:2992 - ++++++++++ have dt= "2015-04-02T13:00:00+01:00" which is UTC: "2015-04-02T12:00:00Z" so returning: 1427976000 
[W] mKCal::SqliteStorage::toOriginTime:2992 - ++++++++++ have dt= "2015-04-02T14:00:00+01:00" which is UTC: "2015-04-02T13:00:00Z" so returning: 1427979600

That is, the input datetime is actually being interpretted differently depending on the device's current timezone...

**Comment by pvuorela** [comment] 2015-04-20 13:19
Test app appears to print wrong +1 timezone already before data reaches sqlite database. Can be also reproduced by replacing ExtendedCalendar and ExtendedStorage with a MemoryCalendar. Thus feels like a KCalCore bug.

Alternatively creating event manually seems to work ok, hinting that the bug could be somewhere around ical handling side.

Tried:

    KCalCore::Event::Ptr event = KCalCore::Event::Ptr(new KCalCore::Event);
    event->setSummary("summary text");
    KTimeZone tz = KSystemTimeZones::zone("Europe/Berlin");
    KDateTime start(QDate(2015, 4, 2), QTime(13, 00), KDateTime::Spec(tz));
    event->setDtStart(start);
    event->setDtEnd(start.addSecs(1000));
    calendar->addEvent(event);

In addition to Berlin, wrong timezone seems to trigger on any instance of CET.

**Comment by pvuorela** [comment] 2015-04-20 16:29
FWIW, also seems to work if I remove the VTIMEZONE part from the data.

**Comment by lenggi** [comment] 2015-05-17 16:08
Based on your comments, I started debugging with the above program. The problem seems to be in the parsing of the timezone provided in the ical message. This can be seen with the following test program

```

#include <QDebug>

#include <memorycalendar.h>
#include <notebook.h>
#include <icalformat.h>
#include <icaltimezones.h>


int main()
{

    QByteArray icalData =
            "BEGIN:VCALENDAR\r\n"
            "VERSION:2.0\r\n"
            "PRODID:-//EGroupware//NONSGML EGroupware Calendar 1.9.004//DE\r\n"
            "BEGIN:VTIMEZONE\r\n"
            "TZID:Europe/Berlin\r\n"
            "X-LIC-LOCATION:Europe/Berlin\r\n"
            "BEGIN:DAYLIGHT\r\n"
            "TZOFFSETFROM:+0100\r\n"
            "TZOFFSETTO:+0200\r\n"
            "TZNAME:CEST\r\n"
            "DTSTART:19700329T020000\r\n"
            "RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3\r\n"
            "END:DAYLIGHT\r\n"
            "BEGIN:STANDARD\r\n"
            "TZOFFSETFROM:+0200\r\n"
            "TZOFFSETTO:+0100\r\n"
            "TZNAME:CET\r\n"
            "DTSTART:19701025T030000\r\n"
            "RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10\r\n"
            "END:STANDARD\r\n"
            "END:VTIMEZONE\r\n"
            "END:VCALENDAR\r\n\r\n";

    KCalCore::ICalFormat iCalFormat;
    KCalCore::MemoryCalendar::Ptr calendar = KCalCore::MemoryCalendar::Ptr(new KCalCore::MemoryCalendar(KDateTime::Spec::UTC()));
    if (!iCalFormat.fromString(calendar, icalData)) {
        qWarning() << "ical import failed!";
        return 1;
    }

    KCalCore::ICalTimeZoneSource tzsource;
    KCalCore::ICalTimeZone berlinSystem = tzsource.standardZone( "Europe/Berlin" );

    KCalCore::ICalTimeZones *tzlist = calendar->timeZones();
    KCalCore::ICalTimeZone berlinParsed = tzlist->zone("Europe/Berlin");

    QDateTime myTime = QDateTime( QDate( 2015, 05, 01 ), QTime( 14, 00, 00 ), Qt::UTC);

    KDateTime::Spec timeSpecSystem = KDateTime::Spec( berlinSystem );
    KDateTime::Spec timeSpecParsed = KDateTime::Spec( berlinParsed );

    qWarning() << "system timezone for" << myTime.toString() << "gets you" << timeSpecSystem.timeZone().toZoneTime(myTime).toString();
    qWarning() << "parsed timezone for" << myTime.toString() << "gets you" << timeSpecParsed.timeZone().toZoneTime(myTime).toString();
    calendar->close();
    return 0;
}
```

Unfortunately, I'm a complete noob when it comes to qt, mer, and sailfishOS. I do not think that I can further debug this in kcalcore as I wouldn't know where to start to get a development environment up and running.
Do you have any ideas where I should report this? Or can anyone of you take care of it?
Thank you very much for your help.

**Comment by chriadam** [comment] 2015-05-19 01:47
Thanks, I'm investigating this one a bit further today.

The problematic codepath is:

icalproperty_get_dtstart() returns null, called from
ICalTimeZoneSourcePrivate::parsePhase() in the ICAL_DTSTART_PROPERTY case, called from
ICalTimeZoneSource::parse() in the ICAL_XDAYLIGHT_COMPONENT case, called from
ICalFormatImpl::populate(), called from
ICalFormat::fromRawString(), called from
ICalFormat::fromString() which is the entrypoint.

It seems that for whatever reason, libical is unable to parse the DTSTART in the DAYLIGHT section containing an RRULE, and thus when it attempts to calculate the set of transitions which occur between (DTSTART, maxDate) it comes up empty.

This causes other problems later on (it ends up discarding all of the transitions back to STANDARD time, since the phase (ie, DST/utcOffset is identical between each of those transitions, because of the lack of DAYLIGHT transitions occurring in between) but those problems are symptomatic of the base cause I described above.

**Comment by chriadam** [comment] 2015-05-19 01:52
Ok, it's interesting: it returns the correct value for the normalized (utc) time.  Thus, we can work around this issue in kcalcore by taking the UTC dtStart and determining local time from it.

I'll have a PR up shortly, but it won't be in this repository.  I'll link to it from this issue, however.

**Comment by chriadam** [comment] 2015-05-19 02:06
https://github.com/mer-packages/kcalcore/pull/7

**Comment by lenggi** [comment] 2015-06-10 16:09
Just to keep this up-to-date: I've added a PR that makes ICalTimeZoneSourcePrivate::parsePhase using UTC times: mer-packages/kcalcore#9

**Comment by chriadam** [comment] 2015-08-03 02:23
That one has been merged into mer-packages-kcalcore and tagged for release as version mer/4.10.2+9git10.  Thank you very much for your contribution.  Closing this issue.

**Closed by chriadam** 2015-08-03 02:23 UTC
